branches:
  only:
    - feature-theme-deepexi
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
script:
- yarn deploy:build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: examples/element-ui
  github-token: $GITHUB_TOKEN
  on:
    branch: feature-theme-deepexi
